# Generated by Django 5.0.6 on 2024-07-24 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'), #here these two fileds are added and it needs home app and 0001_initial file as a dependencies
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='address',
            field=models.TextField(blank=True, null=True), #it shows where we have altered
        ),
    ]
